language: javascript
jdk:
  -openjdk12
  
script: npm install



jobs: 
  include:
    - stage: Build
      script: nodemon server.js
      
  include:
    - stage: Test
      script: mocha ./test/unit-tests
